services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-mock_key}
    # We remove the depends_on since we aren't using Redis yet
    restart: unless-stopped

 postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: autoscrum_db
      POSTGRES_USER: autoscrum_user
      POSTGRES_PASSWORD: autoscrum_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: